# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#HttpOnly_aur.archlinux.org	FALSE	/	TRUE	1461907652	AURSID	91b41448d53cbf973585df54dfef855c
aur.archlinux.org	FALSE	/	FALSE	1461907652	AURLANG	en
